@baseUrl = http://localhost:5001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5N2ExZmU3NjQxODBmZjI5OWIxM2YxMCIsImlhdCI6MTc2OTc3ODY1OCwiZXhwIjoxNzcyMzcwNjU4fQ.2ag3VqPp5SreY2uOj0Mrz6h5jXvtJs1kEjJoccELdVM
@workspaceId = 697cb516348666954f5f67fa
@projectId = 697cb575db0d82a980ff69f8

### Create project
POST {{baseUrl}}/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Backend API",
  "workspaceId": "{{workspaceId}}"
}

### Get projects in workspace
GET {{baseUrl}}/projects/workspace/{{workspaceId}}
Authorization: Bearer {{token}}
