@baseUrl = http://localhost:5001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5N2ExZmU3NjQxODBmZjI5OWIxM2YxMCIsImlhdCI6MTc2OTc3ODY1OCwiZXhwIjoxNzcyMzcwNjU4fQ.2ag3VqPp5SreY2uOj0Mrz6h5jXvtJs1kEjJoccELdVM
@projectId = 697cb575db0d82a980ff69f8
@assigneeId = 697ca6b3d51ec34b58e686ae

### Create task
POST {{baseUrl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Setup auth middleware",
  "projectId": "{{projectId}}",
  "assignee": "{{assigneeId}}"
}

### Get project tasks
GET {{baseUrl}}/tasks/project/{{projectId}}
Authorization: Bearer {{token}}
