@baseUrl = http://localhost:5001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5N2ExZmU3NjQxODBmZjI5OWIxM2YxMCIsImlhdCI6MTc2OTc3ODY1OCwiZXhwIjoxNzcyMzcwNjU4fQ.2ag3VqPp5SreY2uOj0Mrz6h5jXvtJs1kEjJoccELdVM
@workspaceId = 697ca61cd51ec34b58e686a8

POST {{baseUrl}}/workspaces
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Team alpha"
}

###
GET {{baseUrl}}/workspaces/{{workspaceId}}
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/workspaces/{{workspaceId}}/members
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "697ca6b3d51ec34b58e686ae"
}

### Delete workspace (OWNER only)
DELETE {{baseUrl}}/workspaces/{{workspaceId}}
Authorization: Bearer {{token}}

